[package]

name = "cpython"
version = "0.0.5"
description = "Bindings to Python"
authors = ["Daniel Grunwald <daniel@danielgrunwald.de>"]
readme = "README.md"
keywords = [
    "python",
    "cpython",
    "libpython27",
]
homepage = "https://github.com/dgrunwald/rust-cpython"
repository = "https://github.com/dgrunwald/rust-cpython.git"
documentation = "http://dgrunwald.github.io/rust-cpython/doc/cpython/"
license = "MIT"
exclude = [
    ".gitignore",
    ".travis.yml",
    "appveyor.yml",
    ".cargo/config",
    "python27-sys",
    "python3-sys",
]
build = "build.rs"

[dependencies]
libc = "0.2"
num-traits = "0.1"

# These features are both optional, but you must pick one to 
# indicate which python ffi you are trying to bind to.
[dependencies.python27-sys]
optional = true
path = "python27-sys"
version = "0.1.1"

[dependencies.python3-sys]
optional = true
path = "python3-sys"
version = "0.1.2"

[features]
default = ["python27-sys"]

# Enable additional features that require nightly rust
nightly = []

# Optional features to support explicitly specifying python minor version.
# If you don't care which minor version, just specify python3-sys as a 
# feature.
python-3-5 = ["python3-sys/python-3-5"]
python-3-4 = ["python3-sys/python-3-4"]

#pep-384 = ["python3-sys/pep-384"]

